---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  namespace: ide
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: service
        image: image-name
        ports:
        - containerPort: <port-num>
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: python
  namespace: ide
spec:
  type: NodePort
  selector:
    app: python
  ports:
  - protocol: TCP
    port: <port-num>
    targetPort: <port-num>
    nodePort: <port-num>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  namespace: ide
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cplus
  template:
    metadata:
      labels:
        app: cplus
    spec:
      containers:
      - name: service
        image: <image-name>
        ports:
        - containerPort: <port-num>
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cplus
  namespace: ide
spec:
  type: NodePort
  selector:
    app: cplus
  ports:
  - protocol: TCP
    port: <port-num>
    targetPort: <port-num>
    nodePort: <port-num>
---
